# https://taskfile.dev
# 
# * test `curl -H "Content-Type: application/json" localhost:8080/api/...`

version: '3'
env:
  db_file: database.db
  

tasks:
  migrate:
    desc: "Migrate the database file"
    cmds:
      - migrate -path migrations -database sqlite3://$db_file up
    silent: true
  run:
    desc: "Run the app"
    cmds:
      #- task: build-frontend
      - go run . -db database.db
  
  build-frontend:
    desc: Build vue frontend
    dir: frontend
    cmds:
      - npm run build

  lint-frontend:
    desc: Lint vue frontend
    dir: frontend
    cmds:
      - npm run lint
  
  serve-frontend:
    desc: Serve vue frontend
    dir: frontend
    cmds:
      - npm run serve