# https://taskfile.dev
# 
# * test `curl -H "Content-Type: application/json" localhost:8080/api/...`

version: '3'
env:
  db_file: database.db
  

tasks:
  migrate:
    desc: "Migrate the database file"
    cmds:
      - migrate -path migrations -database sqlite3://$db_file up
    silent: true
  run:
    desc: "Run the backend"
    cmds:
      - go run . -db database.db